version: '3'

services:
  neo4j:
    image: neo4j:5.8.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    networks:
      - blog
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
#  app:
#    build: .
#    container_name: blog
#    ports:
#      - 8080:8080
#    networks:
#      - blog
#    env_file:
#      - .env
volumes:
  neo4j-data:
    driver: local

networks:
  blog:
    driver: bridge