version: '3'

services:
  neo4j:
    image: neo4j:5.8.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data:/data
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}

volumes:
  neo4j-data:
    driver: local
